// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protos/yolo_service.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Yolo {
  public static partial class YoloService
  {
    static readonly string __ServiceName = "YoloService";

    static readonly grpc::Marshaller<global::Yolo.DetectionRequest> __Marshaller_DetectionRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yolo.DetectionRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Yolo.DetectionResponse> __Marshaller_DetectionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Yolo.DetectionResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::Yolo.DetectionRequest, global::Yolo.DetectionResponse> __Method_Detect = new grpc::Method<global::Yolo.DetectionRequest, global::Yolo.DetectionResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "Detect",
        __Marshaller_DetectionRequest,
        __Marshaller_DetectionResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Yolo.YoloServiceReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of YoloService</summary>
    public abstract partial class YoloServiceBase
    {
      public virtual global::System.Threading.Tasks.Task Detect(global::Yolo.DetectionRequest request, grpc::IServerStreamWriter<global::Yolo.DetectionResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for YoloService</summary>
    public partial class YoloServiceClient : grpc::ClientBase<YoloServiceClient>
    {
      /// <summary>Creates a new client for YoloService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public YoloServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for YoloService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public YoloServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected YoloServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected YoloServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual grpc::AsyncServerStreamingCall<global::Yolo.DetectionResponse> Detect(global::Yolo.DetectionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Detect(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncServerStreamingCall<global::Yolo.DetectionResponse> Detect(global::Yolo.DetectionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_Detect, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override YoloServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new YoloServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(YoloServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Detect, serviceImpl.Detect).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    // public static void BindService(grpc::ServiceBinderBase serviceBinder, YoloServiceBase serviceImpl)
    // {
    //   serviceBinder.AddMethod(__Method_Detect, serviceImpl.Detect);
    // }
  }
}
#endregion
